Repository gradle/gradle-profiler, pull requests merged in 2020-07, with the labels that each got.

#215 Fix Kotlin non-abi-change mutator so it produces a non-abi-change for java consumers
  src/main/java/org/gradle/profiler/mutations/ApplyNonAbiChangeToKotlinSourceFileMutator.java
  src/test/groovy/org/gradle/profiler/mutations/ApplyNonAbiChangeToKotlinSourceFileMutatorTest.groovy
  src/test/groovy/org/gradle/profiler/mutations/ApplyNonAbiChangeToSourceFileMutatorTest.groovy
Labels: bug

#218 Use Gradle Enterprise conventions plugin
  .teamcity/settings.kts
  .teamcity/settings/GradleProfilerPublishing.kt
  .teamcity/settings/GradleProfilerTest.kt
  .teamcity/settings/extensions.kt
  gradle/init-scripts/build-scan-gradle-internal-server.init.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle.kts
Labels: @execution, internal

#220 Use reproducible JARs for the packaged artifacts
  build.gradle.kts
Labels: @execution

#222 Use canonical paths for temp-files
  src/main/java/org/gradle/profiler/DefaultGradleBuildConfigurationReader.java
  src/main/java/org/gradle/profiler/GeneratedInitScript.java
  src/main/java/org/gradle/profiler/instrument/GradleInstrumentation.java
Labels: @execution, bug

#221 Some usability improvements
  README.md
  src/main/java/org/gradle/profiler/CommandLineParser.java
  src/main/java/org/gradle/profiler/CompositeProfiler.java
  src/main/java/org/gradle/profiler/CompositeProfilerFactory.java
  src/main/java/org/gradle/profiler/GradleScenarioDefinition.java
  src/main/java/org/gradle/profiler/Profiler.java
  src/main/java/org/gradle/profiler/ProfilerFactory.java
  src/main/java/org/gradle/profiler/ScenarioLoader.java
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfiler.java
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfilerDownload.java
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfilerFactory.java
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfilerHeapAllocationProfilerFactory.java
  src/main/java/org/gradle/profiler/buildscan/BuildScanProfiler.java
  src/main/java/org/gradle/profiler/buildscan/BuildScanProfilerFactory.java
  src/main/java/org/gradle/profiler/chrometrace/ChromeTraceProfilerFactory.java
  src/main/java/org/gradle/profiler/jfr/JfrProfiler.java
  src/main/java/org/gradle/profiler/jfr/JfrProfilerFactory.java
  src/main/java/org/gradle/profiler/jprofiler/JProfilerProfiler.java
  src/main/java/org/gradle/profiler/jprofiler/JProfilerProfilerFactory.java
  src/main/java/org/gradle/profiler/mutations/ClearJarsCacheMutator.java
  src/main/java/org/gradle/profiler/yourkit/YourKitHeapAllocationProfilerFactory.java
  src/main/java/org/gradle/profiler/yourkit/YourKitProfiler.java
  src/main/java/org/gradle/profiler/yourkit/YourKitSamplingProfilerFactory.java
  src/main/java/org/gradle/profiler/yourkit/YourKitTracingProfilerFactory.java
  src/test/groovy/org/gradle/profiler/AbstractProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/AsyncProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/mutations/ClearJarsCacheMutatorTest.groovy
Labels: enhancement
