Repository gradle/gradle-profiler, pull requests merged in 2020-12, with the labels that each got.

#299 Run some tests on Java 11
  .teamcity/settings/GradleProfilerPublishing.kt
  .teamcity/settings/GradleProfilerTest.kt
  .teamcity/settings/extensions.kt
  .teamcity/settings/root-project.kt
  build.gradle.kts
  src/test/groovy/org/gradle/profiler/AbstractProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/BuildOperationInstrumentationIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/JFRProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/ProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/ScenarioLoaderTest.groovy
Labels: @execution, internal

#297 Fix pid instrumentation on Eclipse J9
  subprojects/build-operations/build.gradle
  subprojects/build-operations/build.gradle.kts
  subprojects/build-operations/src/main/java/org/gradle/trace/pid/AbstractPidCollectorBuildService.java
  subprojects/build-operations/src/main/java/org/gradle/trace/pid/PidCollector.java
  subprojects/build-operations/src/main/java/org/gradle/trace/pid/PidCollectorBuildService.java
  subprojects/build-operations/src/main/java/org/gradle/trace/pid/PidCollectorJava8BuildService.java
Labels: @execution, bug

#295 Allow configuration cache state to be cleaned up between builds
  src/main/java/org/gradle/profiler/mutations/ClearConfigurationCacheStateMutator.java
Labels: enhancement

#301 Fix master failures
  src/test/groovy/org/gradle/profiler/AbstractProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/ProfilerIntegrationTest.groovy
Labels: no-changelog
