Repository gradle/gradle-profiler, pull requests merged in 2020-10, with the labels that each got.

#277 Measure garbage collection time
  README.md
  src/main/java/org/gradle/profiler/BuildUnderTestInvoker.java
  src/main/java/org/gradle/profiler/CommandLineParser.java
  src/main/java/org/gradle/profiler/CompositeProfiler.java
  src/main/java/org/gradle/profiler/GradleBuildInvocationResult.java
  src/main/java/org/gradle/profiler/GradleScenarioInvoker.java
  src/main/java/org/gradle/profiler/InvocationSettings.java
  src/main/java/org/gradle/profiler/buildops/BuildOperationInstrumentation.java
  src/test/groovy/org/gradle/profiler/ScenarioLoaderTest.groovy
  subprojects/build-operations/src/main/java/org/gradle/trace/buildops/BuildOperationTrace.java
Labels: @execution, enhancement

#276 Release automatically to SDKMAN
  .teamcity/settings.kts
  .teamcity/settings/GradleProfilerPublishing.kt
  .teamcity/settings/root-project.kt
  RELEASING.md
  build.gradle.kts
  gradle.properties
Labels: @execution, internal

#278 Use a BuildService to measure garbage collection time
  README.md
  src/main/java/org/gradle/profiler/GradleScenarioDefinition.java
  src/test/groovy/org/gradle/profiler/BuildOperationInstrumentationIntegrationTest.groovy
  subprojects/build-operations/src/main/java/org/gradle/trace/buildops/BuildOperationTrace.java
Labels: @execution, internal

#280 Add ToolingApiGradleClient.runOperation
  src/main/java/org/gradle/profiler/ToolingApiGradleClient.java
Labels: @execution, internal

#284 Gracefully ignore non-existent build operations
  README.md
  src/test/groovy/org/gradle/profiler/BuildOperationInstrumentationIntegrationTest.groovy
  subprojects/build-operations/src/main/java/org/gradle/trace/buildops/BuildOperationTrace.java
Labels: @execution, enhancement

#290 Support passing JVM arguments with spaces to the Gradle daemon
  .github/workflows/enforce-labels.yml
  src/main/java/org/gradle/profiler/CliGradleClient.java
  src/test/groovy/org/gradle/profiler/GradleInvocationIntegrationTest.groovy
Labels: bug
