Repository gradle/gradle-profiler, pull requests merged in 2020-09, with the labels that each got.

#235 Revert "Expose projectDir in BuildContext and ScenarioContext"
  src/main/java/org/gradle/profiler/DefaultBuildContext.java
  src/main/java/org/gradle/profiler/DefaultScenarioContext.java
  src/main/java/org/gradle/profiler/ScenarioContext.java
  src/test/groovy/org/gradle/profiler/mutations/AbstractMutatorTest.groovy
Labels: @execution

#238 Fix PID instrumentation for configuration caching
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/test/groovy/org/gradle/profiler/AbstractProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/BuildOperationInstrumentationIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/PidInstrumentationIntegrationTest.groovy
  subprojects/build-operations/src/main/java/org/gradle/trace/pid/PidCollector.java
  subprojects/build-operations/src/main/java/org/gradle/trace/pid/PidCollectorBuildService.java
Labels: @execution, bug

#239 Improve report rendering
  src/main/java/org/gradle/profiler/report/HtmlGenerator.java
Labels: @execution

#241 Fix scenario order bug
  src/main/java/org/gradle/profiler/BenchmarkResultCollector.java
  src/main/java/org/gradle/profiler/Main.java
  src/main/java/org/gradle/profiler/ScenarioInvoker.java
  src/main/java/org/gradle/profiler/report/BenchmarkResult.java
  src/main/java/org/gradle/profiler/report/BuildScenarioResult.java
  src/main/java/org/gradle/profiler/report/CsvGenerator.java
  src/main/java/org/gradle/profiler/report/HtmlGenerator.java
Labels: @execution

#248 Add --help option
  src/main/java/org/gradle/profiler/CommandLineParser.java
Labels: @execution, enhancement

#242 Use an HTML template for the report
  build.gradle.kts
  src/main/java/org/gradle/profiler/BenchmarkResultCollector.java
  src/main/java/org/gradle/profiler/BuildScenarioResultImpl.java
  src/main/java/org/gradle/profiler/report/HtmlGenerator.java
  src/main/java/org/gradle/profiler/report/JsonResultWriter.java
  src/main/resources/org/gradle/profiler/report/report-template.html
  src/test/groovy/org/gradle/profiler/report/JsonResultWriterTest.groovy
Labels: @execution, enhancement

#250 Show cross-hair in HTML report
  src/main/resources/org/gradle/profiler/report/report-template.html
Labels: @execution, enhancement

#249 Reduce build operation measurement overhead
  src/main/java/org/gradle/profiler/buildops/BuildOperationInstrumentation.java
  subprojects/build-operations/src/main/java/org/gradle/trace/buildops/BuildOperationTrace.java
Labels: @execution, bug

#251 Report profiler version
  build.gradle.kts
  src/main/java/org/gradle/profiler/CommandLineParser.java
  src/main/java/org/gradle/profiler/Main.java
  src/main/java/org/gradle/profiler/Version.java
  src/main/java/org/gradle/profiler/report/JsonResultWriter.java
  src/main/resources/org/gradle/profiler/report/report-template.html
  src/test/groovy/org/gradle/profiler/AbstractIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/AbstractProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/CommandLineIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/report/JsonResultWriterTest.groovy
Labels: @execution, enhancement

#254 Better HTML report model
  build.gradle.kts
  src/main/java/org/gradle/profiler/report/JsonResultWriter.java
  src/main/resources/org/gradle/profiler/report/report-template.html
  src/test/groovy/org/gradle/profiler/report/JsonResultWriterTest.groovy
  src/test/resources/org/gradle/profiler/report/example.json
Labels: @execution, enhancement, internal

#255 Upgrade to Chart.js 3.0.0-beta and improve typography
  build.gradle.kts
  src/main/resources/org/gradle/profiler/report/report-template.html
  src/test/resources/org/gradle/profiler/report/example-with-build-operations.json
  src/test/resources/org/gradle/profiler/report/example.json
Labels: @execution, enhancement

#253 Refactoring to prepare for improving support for Android Studio sync
  src/main/java/org/gradle/profiler/AndroidStudioSyncAction.java
  src/main/java/org/gradle/profiler/BazelScenarioInvoker.java
  src/main/java/org/gradle/profiler/BuckScenarioInvoker.java
  src/main/java/org/gradle/profiler/BuildAction.java
  src/main/java/org/gradle/profiler/BuildStepAction.java
  src/main/java/org/gradle/profiler/BuildUnderTestInvoker.java
  src/main/java/org/gradle/profiler/CleanupThenStopDaemon.java
  src/main/java/org/gradle/profiler/CliGradleClient.java
  src/main/java/org/gradle/profiler/DefaultGradleBuildConfigurationReader.java
  src/main/java/org/gradle/profiler/GradleBuildInvoker.java
  src/main/java/org/gradle/profiler/GradleClient.java
  src/main/java/org/gradle/profiler/GradleClientSpec.java
  src/main/java/org/gradle/profiler/GradleDaemonReuse.java
  src/main/java/org/gradle/profiler/GradleInvoker.java
  src/main/java/org/gradle/profiler/GradleInvokerBuildAction.java
  src/main/java/org/gradle/profiler/GradleScenarioInvoker.java
  src/main/java/org/gradle/profiler/InstrumentingProfiler.java
  src/main/java/org/gradle/profiler/LoadToolingModelAction.java
  src/main/java/org/gradle/profiler/MavenScenarioInvoker.java
  src/main/java/org/gradle/profiler/RecordingBuildStepAction.java
  src/main/java/org/gradle/profiler/RunBuildStepAction.java
  src/main/java/org/gradle/profiler/RunCleanupStepAction.java
  src/main/java/org/gradle/profiler/RunTasksAction.java
  src/main/java/org/gradle/profiler/ScenarioInvoker.java
  src/main/java/org/gradle/profiler/ScenarioLoader.java
  src/main/java/org/gradle/profiler/StopDaemonAfterAction.java
  src/main/java/org/gradle/profiler/ToolingApiGradleClient.java
  src/main/java/org/gradle/profiler/studio/StudioGradleClient.java
  src/test/groovy/org/gradle/profiler/ScenarioLoaderTest.groovy
Labels: internal

#256 Add more details to HTML report
  build.gradle.kts
  src/main/java/org/gradle/profiler/GradleScenarioDefinition.java
  src/main/java/org/gradle/profiler/report/HtmlGenerator.java
  src/main/java/org/gradle/profiler/report/JsonResultWriter.java
  src/main/resources/org/gradle/profiler/report/report-template.html
  src/test/groovy/org/gradle/profiler/AbstractProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/BenchmarkIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/BuildOperationInstrumentationIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/ProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/report/JsonResultWriterTest.groovy
  src/test/resources/org/gradle/profiler/report/example-regression.json
  src/test/resources/org/gradle/profiler/report/example-with-build-operations.json
  src/test/resources/org/gradle/profiler/report/example.json
Labels: @execution, enhancement

#247 Allow `CliInvoker` redirect build log to file
  gradle.properties
  src/main/java/org/gradle/profiler/CliGradleClient.java
  src/main/java/org/gradle/profiler/CommandExec.java
  src/main/java/org/gradle/profiler/GradleClientSpec.java
Labels: internal

#252 Support passing toolHome to Maven/Buck/Bazel invoker
  src/main/java/org/gradle/profiler/BazelScenarioDefinition.java
  src/main/java/org/gradle/profiler/BazelScenarioInvoker.java
  src/main/java/org/gradle/profiler/BuckScenarioDefinition.java
  src/main/java/org/gradle/profiler/BuckScenarioInvoker.java
  src/main/java/org/gradle/profiler/BuildToolCommandLineInvoker.java
  src/main/java/org/gradle/profiler/BuildToolCommandLineScenarioDefinition.java
  src/main/java/org/gradle/profiler/GradleBuildConfiguration.java
  src/main/java/org/gradle/profiler/MavenScenarioDefinition.java
  src/main/java/org/gradle/profiler/MavenScenarioInvoker.java
  src/main/java/org/gradle/profiler/ScenarioDefinition.java
  src/main/java/org/gradle/profiler/ScenarioInvoker.java
  src/main/java/org/gradle/profiler/ScenarioLoader.java
  src/test/groovy/org/gradle/profiler/ScenarioLoaderTest.groovy
Labels: enhancement

#258 Choose baseline in HTML report
  .gitignore
  build.gradle.kts
  package-lock.json
  package.json
  src/main/java/org/gradle/profiler/BenchmarkResultCollector.java
  src/main/java/org/gradle/profiler/BuildScenarioResultImpl.java
  src/main/java/org/gradle/profiler/report/BuildScenarioResult.java
  src/main/java/org/gradle/profiler/report/CsvGenerator.java
  src/main/java/org/gradle/profiler/report/HtmlGenerator.java
  src/main/java/org/gradle/profiler/report/JsonResultWriter.java
  src/main/js/org/gradle/profiler/report/report.js
  src/main/resources/org/gradle/profiler/report/report-template.html
  src/test/groovy/org/gradle/profiler/AbstractProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/BenchmarkIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/BenchmarkResultCollectorTest.groovy
  src/test/groovy/org/gradle/profiler/BuildOperationInstrumentationIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/ProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/report/JsonResultWriterTest.groovy
  src/test/resources/org/gradle/profiler/report/example-single.json
  src/test/resources/org/gradle/profiler/report/example-with-build-operations.json
  src/test/resources/org/gradle/profiler/report/example.json
Labels: @execution, enhancement

#259 Add support for profiling and benchmarking Android Studio sync
  README.md
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  buildSrc/src/main/kotlin/profiler.embedded-library.gradle.kts
  buildSrc/src/main/kotlin/profiler.java-library.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle.kts
  src/main/java/org/gradle/profiler/AndroidStudioSyncAction.java
  src/main/java/org/gradle/profiler/CommandExec.java
  src/main/java/org/gradle/profiler/CommandLineParser.java
  src/main/java/org/gradle/profiler/DefaultGradleBuildConfigurationReader.java
  src/main/java/org/gradle/profiler/GradleClientSpec.java
  src/main/java/org/gradle/profiler/GradleScenarioInvoker.java
  src/main/java/org/gradle/profiler/InvocationSettings.java
  src/main/java/org/gradle/profiler/ScenarioLoader.java
  src/main/java/org/gradle/profiler/ToolingApiGradleClient.java
  src/main/java/org/gradle/profiler/instrument/GradleInstrumentation.java
  src/main/java/org/gradle/profiler/studio/LaunchConfiguration.java
  src/main/java/org/gradle/profiler/studio/LauncherConfigurationParser.java
  src/main/java/org/gradle/profiler/studio/StudioGradleClient.java
  src/test/groovy/org/gradle/profiler/ScenarioLoaderTest.groovy
  subprojects/build-operations/build.gradle
  subprojects/chrome-trace/build.gradle
  subprojects/client-protocol/build.gradle.kts
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/Client.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/Connection.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/ConnectionParameters.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/Message.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/Serializer.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/Server.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/ServerConnection.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/SyncCompleted.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/SyncParameters.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/SyncStarted.java
  subprojects/client-protocol/src/test/groovy/org/gradle/profiler/client/protocol/ProtocolTest.groovy
  subprojects/instrumentation-support/build.gradle.kts
  subprojects/instrumentation-support/src/main/java/org/gradle/profiler/studio/instrumented/Interceptor.java
  subprojects/instrumentation-support/src/main/java/org/gradle/profiler/studio/instrumented/RecordingResultHandler.java
  subprojects/studio-agent/build.gradle.kts
  subprojects/studio-agent/src/main/java/org/gradle/profiler/studio/agent/Agent.java
Labels: enhancement

#263 Show scenario title on graph labels
  src/main/js/org/gradle/profiler/report/report.js
Labels: @execution, enhancement

#266 Disable JFR tests on macOS
  src/test/groovy/org/gradle/profiler/JFRProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/ProfilerIntegrationTest.groovy
Labels: @execution, internal

#262 Support generating flame graphs from multiple jfr files
  src/main/java/org/gradle/profiler/InstrumentingProfiler.java
  src/main/java/org/gradle/profiler/jfr/JFRJvmArgsCalculator.java
  src/main/java/org/gradle/profiler/jfr/JfrFlameGraphGenerator.java
  src/main/java/org/gradle/profiler/jfr/JfrProfiler.java
  src/main/java/org/gradle/profiler/jfr/JfrToStacksConverter.java
  src/main/java/org/gradle/profiler/jprofiler/JProfilerProfiler.java
  src/main/java/org/gradle/profiler/yourkit/YourKitProfiler.java
  src/test/groovy/org/gradle/profiler/JFRProfilerIntegrationTest.groovy
Labels: enhancement

#264 Show benchmark title in HTML report
  src/main/java/org/gradle/profiler/BenchmarkResultCollector.java
  src/main/java/org/gradle/profiler/CommandLineParser.java
  src/main/java/org/gradle/profiler/InvocationSettings.java
  src/main/java/org/gradle/profiler/Main.java
  src/main/java/org/gradle/profiler/report/AbstractGenerator.java
  src/main/java/org/gradle/profiler/report/CsvGenerator.java
  src/main/java/org/gradle/profiler/report/HtmlGenerator.java
  src/main/java/org/gradle/profiler/report/JsonResultWriter.java
  src/main/js/org/gradle/profiler/report/report.js
  src/main/resources/org/gradle/profiler/report/report-template.html
  src/test/groovy/org/gradle/profiler/BenchmarkResultCollectorTest.groovy
  src/test/groovy/org/gradle/profiler/report/JsonResultWriterTest.groovy
  src/test/resources/org/gradle/profiler/report/example-regression.json
  src/test/resources/org/gradle/profiler/report/example-single.json
  src/test/resources/org/gradle/profiler/report/example-with-build-operations.json
  src/test/resources/org/gradle/profiler/report/example.json
Labels: @execution, enhancement

#267 Extract publication logic to buildSrc
  build.gradle.kts
  buildSrc/src/main/kotlin/profiler.publication.gradle.kts
  subprojects/client-protocol/build.gradle.kts
Labels: internal

#268 Fix two issues with Android Studio Sync support
  src/main/java/org/gradle/profiler/studio/LauncherConfigurationParser.java
  src/main/java/org/gradle/profiler/studio/StudioGradleClient.java
Labels: no-changelog

#271 Automate tagging when publishing plugin
  .teamcity/settings/GradleProfilerPublishing.kt
  build.gradle.kts
Labels: internal

#273 Remove all of the transforms cache dir
  src/main/java/org/gradle/profiler/mutations/ClearArtifactTransformCacheMutator.java
Labels: @execution, internal

#274 Do not allow cleanup actions to run between builds with warm daemon
  .editorconfig
  src/main/java/org/gradle/profiler/AdhocGradleScenarioDefinition.java
  src/main/java/org/gradle/profiler/BazelScenarioDefinition.java
  src/main/java/org/gradle/profiler/BuckScenarioDefinition.java
  src/main/java/org/gradle/profiler/BuildInvoker.java
  src/main/java/org/gradle/profiler/BuildMutator.java
  src/main/java/org/gradle/profiler/BuildMutatorFactory.java
  src/main/java/org/gradle/profiler/BuildToolCommandLineInvoker.java
  src/main/java/org/gradle/profiler/BuildToolCommandLineScenarioDefinition.java
  src/main/java/org/gradle/profiler/GradleBuildInvoker.java
  src/main/java/org/gradle/profiler/GradleScenarioDefinition.java
  src/main/java/org/gradle/profiler/GradleScenarioInvoker.java
  src/main/java/org/gradle/profiler/MavenScenarioDefinition.java
  src/main/java/org/gradle/profiler/ScenarioDefinition.java
  src/main/java/org/gradle/profiler/ScenarioLoader.java
  src/main/java/org/gradle/profiler/mutations/AbstractBuildMutatorWithoutOptionsConfigurator.java
  src/main/java/org/gradle/profiler/mutations/AbstractCleanupMutator.java
  src/main/java/org/gradle/profiler/mutations/BuildMutatorConfigurator.java
  src/main/java/org/gradle/profiler/mutations/ClearArtifactTransformCacheMutator.java
  src/main/java/org/gradle/profiler/mutations/ClearBuildCacheMutator.java
  src/main/java/org/gradle/profiler/mutations/ClearConfigurationCacheStateMutator.java
  src/main/java/org/gradle/profiler/mutations/ClearGradleUserHomeMutator.java
  src/main/java/org/gradle/profiler/mutations/ClearJarsCacheMutator.java
  src/main/java/org/gradle/profiler/mutations/ClearProjectCacheMutator.java
  src/main/java/org/gradle/profiler/mutations/FileChangeMutatorConfigurator.java
  src/main/java/org/gradle/profiler/mutations/GitCheckoutMutator.java
  src/main/java/org/gradle/profiler/mutations/GitRevertMutator.java
  src/main/java/org/gradle/profiler/mutations/ShowBuildCacheSizeMutator.java
  src/main/java/org/gradle/profiler/report/JsonResultWriter.java
  src/main/resources/org/gradle/profiler/report/report-template.html
  src/test/groovy/org/gradle/profiler/ProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/ScenarioLoaderTest.groovy
  src/test/groovy/org/gradle/profiler/report/JsonResultWriterTest.groovy
  src/test/resources/org/gradle/profiler/report/example-regression.json
  src/test/resources/org/gradle/profiler/report/example-single.json
  src/test/resources/org/gradle/profiler/report/example-with-build-operations.json
  src/test/resources/org/gradle/profiler/report/example.json
Labels: @execution, internal
