Repository gradle/gradle-profiler, pull requests merged in 2021-08, with the labels that each got.

#345 Allow running tasks without "githubToken"
  build.gradle.kts
Labels: @execution, bug

#346 Use newer version of flightrecorder
  build.gradle.kts
Labels: internal

#343 Publish artifact to Maven Central
  .github/release-drafter.yml
  .teamcity/settings/GradleProfilerPublishing.kt
  build.gradle.kts
  buildSrc/src/main/kotlin/profiler.publication.gradle.kts
  gradle.properties
Labels: enhancement, @execution

#350 Replace reference to repo.gradle.org
  buildSrc/src/main/kotlin/profiler.java-library.gradle.kts
Labels: no-changelog

#341 Use version catalog instead of homegrown solution
  build.gradle.kts
  buildSrc/src/main/kotlin/profiler.java-library.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
  subprojects/client-protocol/build.gradle.kts
  subprojects/instrumentation-support/build.gradle.kts
Labels: @execution, internal

#353 Drop unused credentials
  .teamcity/settings/GradleProfilerPublishing.kt
Labels: internal, no-changelog
