Repository gradle/gradle-profiler, pull requests merged in 2021-03, with the labels that each got.

#320 Normalize stack frames with Lambda class names
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfilerController.java
  src/main/java/org/gradle/profiler/flamegraph/FlameGraphSanitizer.java
  src/main/java/org/gradle/profiler/jfr/JfrFlameGraphGenerator.java
  src/test/groovy/org/gradle/profiler/flamegraph/FlameGraphSanitizerTest.groovy
Labels: enhancement

#322 Do not publish snapshots or alphas to SDKman
  build.gradle.kts
Labels: internal

#321 Update to the same version of javaparser as gradle/gradle
  build.gradle.kts
  src/main/java/org/gradle/profiler/mutations/AbstractJavaSourceFileMutator.java
  src/main/java/org/gradle/profiler/mutations/ApplyAbiChangeToJavaSourceFileMutator.java
  src/main/java/org/gradle/profiler/mutations/ApplyNonAbiChangeToJavaSourceFileMutator.java
  src/test/groovy/org/gradle/profiler/ProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/mutations/ApplyAbiChangeToJavaSourceFileMutatorTest.groovy
  src/test/groovy/org/gradle/profiler/mutations/ApplyAbiChangeToSourceFileMutatorTest.groovy
  src/test/groovy/org/gradle/profiler/mutations/ApplyNonAbiChangeToJavaSourceFileMutatorTest.groovy
  src/test/groovy/org/gradle/profiler/mutations/ApplyNonAbiChangeToSourceFileMutatorTest.groovy
  src/test/groovy/org/gradle/profiler/mutations/JavaParserFixture.groovy
Labels: enhancement

#305 Allow apply-cpp-change-to for other file extensions as well
  src/main/java/org/gradle/profiler/mutations/ApplyChangeToNativeSourceFileMutator.java
  src/test/groovy/org/gradle/profiler/mutations/ApplyChangeToNativeSourceFileMutatorTest.groovy
Labels: enhancement

#326 Consolidate file layout for profiles and flame graphs
  src/main/java/org/gradle/profiler/GradleScenarioDefinition.java
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfilerController.java
  src/main/java/org/gradle/profiler/flamegraph/FlameGraphSanitizer.java
  src/main/java/org/gradle/profiler/jfr/JFRControl.java
  src/main/java/org/gradle/profiler/jfr/JFRJvmArgsCalculator.java
  src/main/java/org/gradle/profiler/jfr/JfrFlameGraphGenerator.java
  src/main/java/org/gradle/profiler/jfr/JfrProfiler.java
  src/test/groovy/org/gradle/profiler/AsyncProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/JFRProfilerIntegrationTest.groovy
Labels: enhancement

#328 Support capturing multiple events with async profiler
  README.md
  src/main/java/org/gradle/profiler/ProfilerFactory.java
  src/main/java/org/gradle/profiler/ScenarioSettings.java
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfiler.java
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfilerAllEventsProfilerFactory.java
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfilerConfig.java
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfilerController.java
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfilerDownload.java
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfilerFactory.java
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfilerHeapAllocationProfilerFactory.java
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfilerJvmArgsCalculator.java
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfilerOutputType.java
  src/main/java/org/gradle/profiler/chrometrace/ChromeTraceInstrumentation.java
  src/main/java/org/gradle/profiler/flamegraph/FlameGraphTool.java
  src/main/java/org/gradle/profiler/heapdump/HeapDumpProfiler.java
  src/main/java/org/gradle/profiler/jfr/JFRControl.java
  src/main/java/org/gradle/profiler/jfr/JfrFlameGraphGenerator.java
  src/main/java/org/gradle/profiler/jfr/JfrProfiler.java
  src/main/java/org/gradle/profiler/jfr/JfrToStacksConverter.java
  src/main/java/org/gradle/profiler/jprofiler/JProfiler.java
  src/main/java/org/gradle/profiler/yourkit/YourKitJvmArgsCalculator.java
  src/test/groovy/org/gradle/profiler/AsyncProfilerIntegrationTest.groovy
Labels: enhancement

#329 Create differential flame graphs for async-profiler or JFR
  README.md
  src/main/java/org/gradle/profiler/CommandLineParser.java
  src/main/java/org/gradle/profiler/CompositeProfiler.java
  src/main/java/org/gradle/profiler/InvocationSettings.java
  src/main/java/org/gradle/profiler/Main.java
  src/main/java/org/gradle/profiler/Profiler.java
  src/main/java/org/gradle/profiler/ScenarioLoader.java
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfiler.java
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfilerController.java
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfilerFactory.java
  src/main/java/org/gradle/profiler/flamegraph/DetailLevel.java
  src/main/java/org/gradle/profiler/flamegraph/DifferentialStacksGenerator.java
  src/main/java/org/gradle/profiler/flamegraph/EventType.java
  src/main/java/org/gradle/profiler/flamegraph/FlameGraphGenerator.java
  src/main/java/org/gradle/profiler/flamegraph/FlameGraphTool.java
  src/main/java/org/gradle/profiler/flamegraph/Stacks.java
  src/main/java/org/gradle/profiler/jfr/JFRControl.java
  src/main/java/org/gradle/profiler/jfr/JfrFlameGraphGenerator.java
  src/main/java/org/gradle/profiler/jfr/JfrProfiler.java
  src/main/java/org/gradle/profiler/jfr/JfrToStacksConverter.java
  src/main/resources/org/gradle/profiler/flamegraph/difffolded.pl
  src/main/resources/org/gradle/profiler/flamegraph/flamegraph.pl
  src/test/groovy/org/gradle/profiler/AsyncProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/DifferentialFlameGraphIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/FlameGraphFixture.groovy
  src/test/groovy/org/gradle/profiler/JFRProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/JProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/ProfilerIntegrationTest.groovy
Labels: @execution, enhancement
