Repository gradle/gradle-profiler, pull requests merged in 2021-12, with the labels that each got.

#374 Move Android Studio related code out of GradleScenarioInvoker and rel…
  src/main/java/org/gradle/profiler/BazelScenarioInvoker.java
  src/main/java/org/gradle/profiler/BuckScenarioInvoker.java
  src/main/java/org/gradle/profiler/BuildAction.java
  src/main/java/org/gradle/profiler/BuildToolCommandLineInvoker.java
  src/main/java/org/gradle/profiler/BuildUnderTestInvoker.java
  src/main/java/org/gradle/profiler/GradleBuildInvocationResult.java
  src/main/java/org/gradle/profiler/GradleInvokerBuildAction.java
  src/main/java/org/gradle/profiler/GradleScenarioDefinition.java
  src/main/java/org/gradle/profiler/GradleScenarioInvoker.java
  src/main/java/org/gradle/profiler/Main.java
  src/main/java/org/gradle/profiler/MavenScenarioInvoker.java
  src/main/java/org/gradle/profiler/ScenarioInvoker.java
  src/main/java/org/gradle/profiler/ScenarioLoader.java
  src/main/java/org/gradle/profiler/result/BuildInvocationResult.java
  src/main/java/org/gradle/profiler/studio/StudioGradleClient.java
  src/main/java/org/gradle/profiler/studio/invoker/StudioBuildActionResult.java
  src/main/java/org/gradle/profiler/studio/invoker/StudioBuildInvocationResult.java
  src/main/java/org/gradle/profiler/studio/invoker/StudioGradleScenarioDefinition.java
  src/main/java/org/gradle/profiler/studio/invoker/StudioGradleScenarioInvoker.java
  src/test/groovy/org/gradle/profiler/ScenarioLoaderTest.groovy
  src/test/groovy/org/gradle/profiler/report/JsonResultWriterTest.groovy
Labels: @execution, internal

#380 Fail fast when Android Studio sync fails
  src/main/java/org/gradle/profiler/studio/StudioGradleClient.java
  src/test/groovy/org/gradle/profiler/AndroidStudioIntegrationTest.groovy
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/messages/StudioSyncRequestCompleted.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/serialization/MessageSerializer.java
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/client/GradleProfilerClient.java
Labels: @execution, internal

#382 Fix gc measurements for Android Studio benchmarks
  src/test/groovy/org/gradle/profiler/AndroidStudioIntegrationTest.groovy
  subprojects/build-operations/src/main/java/org/gradle/trace/buildops/BuildOperationTrace.java
Labels: @execution, internal

#383 Use absolute paths for async-profiler output files
  src/main/java/org/gradle/profiler/CommandLineParser.java
Labels: @execution, internal

#384 Add option to override Android Studio jvm args
  README.md
  src/main/java/org/gradle/profiler/GradleClientSpec.java
  src/main/java/org/gradle/profiler/Main.java
  src/main/java/org/gradle/profiler/ScenarioLoader.java
  src/main/java/org/gradle/profiler/studio/StudioGradleClient.java
  src/main/java/org/gradle/profiler/studio/invoker/StudioGradleScenarioDefinition.java
  src/main/java/org/gradle/profiler/studio/invoker/StudioGradleScenarioInvoker.java
  src/main/java/org/gradle/profiler/studio/launcher/LauncherConfigurationParser.java
  src/main/java/org/gradle/profiler/studio/process/StudioProcess.java
  src/main/java/org/gradle/profiler/studio/process/StudioProcessController.java
  src/test/groovy/org/gradle/profiler/AbstractProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/AndroidStudioIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/ScenarioLoaderTest.groovy
Labels: @execution, internal

#385 Output chrome trace file for every invocation
  src/main/java/org/gradle/profiler/BuildUnderTestInvoker.java
  src/main/java/org/gradle/profiler/Phase.java
  src/main/java/org/gradle/profiler/chrometrace/ChromeTraceInstrumentation.java
  src/test/groovy/org/gradle/profiler/ChromeTraceIntegrationTest.groovy
  subprojects/chrome-trace/src/main/java/org/gradle/trace/GradleTracingPlugin.java
Labels: enhancement, @execution

#387 Fix flamegraph.pl for graphs not created with stack diff
  src/main/resources/org/gradle/profiler/flamegraph/flamegraph.pl
Labels: @execution, internal

#386 Automatically install Android SDK on CI
  build.gradle.kts
  buildSrc/src/main/kotlin/extensions/AndroidStudioTestExtension.kt
  buildSrc/src/main/kotlin/profiler.android-studio-setup.gradle.kts
  buildSrc/src/main/kotlin/tasks/InstallAndroidSdkTask.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: @execution, internal

#389 Use a separate job to publish the released version to SDKman
  .gitignore
  .teamcity/settings/GradleProfilerPublishToSdkMan.kt
  .teamcity/settings/GradleProfilerPublishing.kt
  .teamcity/settings/extensions.kt
  .teamcity/settings/root-project.kt
  RELEASING.md
  build.gradle.kts
  buildSrc/src/main/kotlin/extensions.kt
  buildSrc/src/main/kotlin/extensions/VersionInfo.kt
  buildSrc/src/main/kotlin/profiler.allprojects.gradle.kts
  buildSrc/src/main/kotlin/profiler.java-library.gradle.kts
  buildSrc/src/main/kotlin/profiler.versioning-root-project.gradle.kts
  buildSrc/src/main/kotlin/profiler.versioning.gradle.kts
  subprojects/studio-plugin/build.gradle.kts
Labels: no-changelog

#373 Add homebrew as additional installation option
  README.md
Labels: no-changelog

#391 Fix instructions for installing gradle-profiler with Homebrew
  README.md
Labels: no-changelog
