Repository gradle/gradle-profiler, pull requests merged in 2021-11, with the labels that each got.

#364 Allow a scenario to run a tooling API action
  README.md
  buildSrc/src/main/kotlin/profiler.java-library.gradle.kts
  gradle/libs.versions.toml
  src/main/java/org/gradle/profiler/DefaultGradleBuildConfigurationReader.java
  src/main/java/org/gradle/profiler/RunToolingAction.java
  src/main/java/org/gradle/profiler/ScenarioLoader.java
  src/main/java/org/gradle/profiler/ToolingApiGradleClient.java
  src/main/java/org/gradle/profiler/toolingapi/FetchProjectPublications.java
  src/test/groovy/org/gradle/profiler/ProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/ScenarioLoaderTest.groovy
  src/test/groovy/org/gradle/profiler/ToolingApiIntegrationTest.groovy
Labels: enhancement

#367 CI build now always uses Java11 as JAVA_HOME
  .teamcity/settings/GradleProfilerTest.kt
  .teamcity/settings/extensions.kt
  build.gradle.kts
Labels: @execution, internal

#357 Add mutation support for Compose
  README.md
  src/main/java/org/gradle/profiler/ScenarioLoader.java
  src/main/java/org/gradle/profiler/mutations/ApplyChangeToComposableKotlinFileMutator.java
  src/test/groovy/org/gradle/profiler/mutations/ApplyChangeToComposableKotlinFileMutatorTest.groovy
Labels: enhancement

#365 Implement automatic Android studio sync
  README.md
  build.gradle.kts
  buildSrc/build.gradle.kts
  settings.gradle.kts
  src/main/java/org/gradle/profiler/AndroidStudioSyncAction.java
  src/main/java/org/gradle/profiler/BuildAction.java
  src/main/java/org/gradle/profiler/BuildUnderTestInvoker.java
  src/main/java/org/gradle/profiler/CommandExec.java
  src/main/java/org/gradle/profiler/GradleBuildInvocationResult.java
  src/main/java/org/gradle/profiler/GradleInvokerBuildAction.java
  src/main/java/org/gradle/profiler/GradleScenarioDefinition.java
  src/main/java/org/gradle/profiler/GradleScenarioInvoker.java
  src/main/java/org/gradle/profiler/instrument/GradleInstrumentation.java
  src/main/java/org/gradle/profiler/result/BuildInvocationResult.java
  src/main/java/org/gradle/profiler/studio/LaunchConfiguration.java
  src/main/java/org/gradle/profiler/studio/LauncherConfigurationParser.java
  src/main/java/org/gradle/profiler/studio/StudioGradleClient.java
  src/main/java/org/gradle/profiler/studio/plugin/StudioPluginInstaller.java
  src/test/groovy/org/gradle/profiler/AbstractProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/BenchmarkIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/BuildOperationInstrumentationIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/ProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/ToolingApiIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/report/JsonResultWriterTest.groovy
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/Client.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/Message.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/Serializer.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/ServerConnection.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/SyncStarted.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/messages/GradleInvocationCompleted.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/messages/GradleInvocationParameters.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/messages/GradleInvocationStarted.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/messages/Message.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/messages/StudioAgentConnectionParameters.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/messages/StudioRequest.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/messages/StudioSyncRequestCompleted.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/serialization/MessageProtocolHandler.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/serialization/MessageSerializer.java
  subprojects/client-protocol/src/test/groovy/org/gradle/profiler/client/protocol/ProtocolTest.groovy
  subprojects/instrumentation-support/src/main/java/org/gradle/profiler/studio/instrumented/Interceptor.java
  subprojects/instrumentation-support/src/main/java/org/gradle/profiler/studio/instrumented/RecordingResultHandler.java
  subprojects/studio-plugin/build.gradle.kts
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/GradleProfilerProjectManagerListener.java
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/client/GradleProfilerClient.java
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/system/AndroidStudioSystemHelper.java
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/system/GradleProfilerGradleSyncListener.java
  subprojects/studio-plugin/src/main/resources/META-INF/plugin.xml
  subprojects/studio-plugin/src/test/groovy/org/gradle/profiler/studio/plugin/StudioPluginIntegrationTest.groovy
Labels: enhancement, @execution

#366 Add full gradle-profiler with Android Studio integration tests
  README.md
  src/main/java/org/gradle/profiler/CommandLineParser.java
  src/main/java/org/gradle/profiler/InvocationSettings.java
  src/main/java/org/gradle/profiler/studio/LaunchConfiguration.java
  src/main/java/org/gradle/profiler/studio/LauncherConfigurationParser.java
  src/main/java/org/gradle/profiler/studio/StudioGradleClient.java
  src/main/java/org/gradle/profiler/studio/tools/StudioFinder.java
  src/main/java/org/gradle/profiler/studio/tools/StudioPluginInstaller.java
  src/main/java/org/gradle/profiler/studio/tools/StudioSandboxCreator.java
  src/test/groovy/org/gradle/profiler/AndroidStudioIntegrationTest.groovy
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/Client.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/messages/StudioRequest.java
  subprojects/studio-agent/build.gradle.kts
  subprojects/studio-plugin/build.gradle.kts
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/client/GradleProfilerClient.java
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/system/AndroidStudioSystemHelper.java
  subprojects/studio-plugin/src/test/groovy/org/gradle/profiler/studio/plugin/StudioPluginIntegrationTest.groovy
  subprojects/studio-plugin/src/testFixtures/groovy/org/gradle/profiler/studio/plugin/StudioPluginTestCase.groovy
Labels: @execution, internal

#369 Detect if studio was not started sooner
  src/main/java/org/gradle/profiler/studio/LaunchConfiguration.java
  src/main/java/org/gradle/profiler/studio/LauncherConfigurationParser.java
  src/main/java/org/gradle/profiler/studio/StudioGradleClient.java
  src/test/groovy/org/gradle/profiler/AndroidStudioIntegrationTest.groovy
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/Client.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/agent/AgentClientContainer.java
  subprojects/client-protocol/src/test/groovy/org/gradle/profiler/client/protocol/ProtocolTest.groovy
  subprojects/instrumentation-support/src/main/java/org/gradle/profiler/studio/instrumented/Interceptor.java
  subprojects/instrumentation-support/src/main/java/org/gradle/profiler/studio/instrumented/RecordingResultHandler.java
  subprojects/studio-agent/src/main/java/org/gradle/profiler/studio/agent/Agent.java
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/GradleProfilerProjectManagerListener.java
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/client/GradleProfilerClient.java
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/system/AndroidStudioSystemHelper.java
  subprojects/studio-plugin/src/main/resources/META-INF/plugin.xml
  subprojects/studio-plugin/src/test/groovy/org/gradle/profiler/studio/plugin/StudioPluginIntegrationTest.groovy
Labels: @execution, internal

#370 Add option to run Android Studio sync with clean IDE cache
  README.md
  src/main/java/org/gradle/profiler/AndroidStudioSyncAction.java
  src/main/java/org/gradle/profiler/GradleBuildInvoker.java
  src/main/java/org/gradle/profiler/GradleClientSpec.java
  src/main/java/org/gradle/profiler/ScenarioLoader.java
  src/main/java/org/gradle/profiler/studio/LaunchConfiguration.java
  src/main/java/org/gradle/profiler/studio/StudioGradleClient.java
  src/main/java/org/gradle/profiler/studio/process/StudioProcess.java
  src/main/java/org/gradle/profiler/studio/process/StudioProcessController.java
  src/test/groovy/org/gradle/profiler/AndroidStudioIntegrationTest.groovy
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/ServerConnection.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/messages/StudioCacheCleanupCompleted.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/messages/StudioRequest.java
  subprojects/client-protocol/src/main/java/org/gradle/profiler/client/protocol/serialization/MessageSerializer.java
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/GradleProfilerProjectManagerListener.java
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/client/GradleProfilerClient.java
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/system/AndroidStudioSystemHelper.java
  subprojects/studio-plugin/src/test/groovy/org/gradle/profiler/studio/plugin/StudioPluginIntegrationTest.groovy
Labels: enhancement, @execution

#375 Disable Android Studio update for sandbox
  src/main/java/org/gradle/profiler/studio/tools/StudioSandboxCreator.java
  src/main/java/org/gradle/profiler/support/FileSupport.java
  src/test/groovy/org/gradle/profiler/studio/tools/StudioSandboxCreatorTest.groovy
Labels: @execution, internal

#376 Enable parallel builds for gradle-profiler
  gradle.properties
Labels: internal

#372 Add support for running Android Studio profiler with Linux and Windows and running tests on CI/CD
  .teamcity/settings/GradleProfilerTest.kt
  .teamcity/settings/extensions.kt
  build.gradle.kts
  buildSrc/src/main/kotlin/extensions/AndroidStudioTestExtension.kt
  buildSrc/src/main/kotlin/profiler.android-studio-setup.gradle.kts
  src/main/java/org/gradle/profiler/studio/LauncherConfigurationParser.java
  src/main/java/org/gradle/profiler/studio/StudioGradleClient.java
  src/main/java/org/gradle/profiler/studio/launcher/LaunchConfiguration.java
  src/main/java/org/gradle/profiler/studio/launcher/LauncherConfigurationParser.java
  src/main/java/org/gradle/profiler/studio/launcher/StudioConfiguration.java
  src/main/java/org/gradle/profiler/studio/launcher/StudioConfigurationProvider.java
  src/main/java/org/gradle/profiler/studio/process/StudioProcess.java
  src/main/java/org/gradle/profiler/studio/tools/StudioFinder.java
  src/main/java/org/gradle/profiler/studio/tools/StudioPluginInstaller.java
  src/main/java/org/gradle/profiler/studio/tools/StudioSandboxCreator.java
  src/test/groovy/org/gradle/profiler/AndroidStudioIntegrationTest.groovy
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/GradleProfilerPreloadingActivity.java
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/GradleProfilerProjectManagerListener.java
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/starter/HeadlessApplicationStarter.java
  subprojects/studio-plugin/src/main/resources/META-INF/plugin.xml
Labels: enhancement, @execution
