Repository gradle/gradle-profiler, pull requests merged in 2021-07, with the labels that each got.

#336 Produce json file for Chrome trace
  README.md
  src/main/java/org/gradle/profiler/chrometrace/ChromeTraceInstrumentation.java
  src/main/java/org/gradle/profiler/chrometrace/ChromeTraceProfiler.java
  src/test/groovy/org/gradle/profiler/ChromeTraceIntegrationTest.groovy
  subprojects/chrome-trace/src/main/java/org/gradle/trace/AsynchronousTraceWriter.java
  subprojects/chrome-trace/src/main/resources/trace-footer.html
  subprojects/chrome-trace/src/main/resources/trace-header.html
Labels: @execution, enhancement

#337 Support configuration client Gradle VM in CliGradleClient
  gradle.properties
  src/main/java/org/gradle/profiler/CliGradleClient.java
  src/main/java/org/gradle/profiler/GradleBuildConfiguration.java
Labels: enhancement

#339 Upgradle to 7.1.1
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/profiler.java-library.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  src/test/groovy/org/gradle/profiler/AbstractProfilerIntegrationTest.groovy
  src/test/groovy/org/gradle/profiler/ChromeTraceIntegrationTest.groovy
  subprojects/chrome-trace/src/main/java/org/gradle/trace/listener/BuildOperationListenerAdapter.java
  subprojects/chrome-trace/src/main/java/org/gradle/trace/listener/Gradle33BuildOperationListenerAdapter.java
  subprojects/chrome-trace/src/main/java/org/gradle/trace/listener/Gradle35BuildOperationListenerInvocationHandler.java
  subprojects/studio-agent/build.gradle.kts
Labels: @execution, internal

#340 Sign artifacts for publishing
  .teamcity/settings/GradleProfilerPublishing.kt
  buildSrc/src/main/kotlin/profiler.publication.gradle.kts
Labels: @execution, internal

#342 Add additional Metadata and publish Javadocs
  build.gradle.kts
  buildSrc/src/main/kotlin/profiler.publication.gradle.kts
  src/main/java/org/gradle/profiler/mutations/ApplyChangeToAndroidLayoutFileMutator.java
  subprojects/client-protocol/build.gradle.kts
Labels: @execution, internal
