Repository gradle/gradle-profiler, pull requests merged in 2022-08, with the labels that each got.

#438 Upgrade Gradle version to 7.5
  .teamcity/settings/GradleProfilerTest.kt
  .teamcity/settings/root-project.kt
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  src/test/groovy/org/gradle/profiler/AbstractProfilerIntegrationTest.groovy
Labels: @execution, internal

#440 Upgrade to latest gradle enterprise plugin
  settings.gradle.kts
Labels: internal

#439 Add support for Android Studio Chipmunk (2021.2), Dolphin (2021.3) and Electric Eel (2022.1)
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/java/org/gradle/profiler/studio/launcher/LauncherConfigurationParser.java
  src/main/java/org/gradle/profiler/studio/launcher/StudioConfigurationProvider.java
  src/test/groovy/org/gradle/profiler/studio/launcher/StudioConfigurationProviderTest.groovy
  subprojects/studio-plugin/build.gradle.kts
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/GradleProfilerProjectManagerListener.java
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/client/GradleProfilerClient.java
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/system/AndroidStudioSystemHelper.java
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/system/GradleProfilerGradleSyncListener.java
  subprojects/studio-plugin/src/test/groovy/org/gradle/profiler/studio/plugin/StudioPluginIntegrationTest.groovy
  subprojects/studio-plugin/src/testFixtures/groovy/org/gradle/profiler/studio/plugin/IdeSetupHelper.groovy
  subprojects/studio-plugin/src/testFixtures/groovy/org/gradle/profiler/studio/plugin/StudioPluginSpecification.groovy
Labels: enhancement, @execution

#442 Fix parsing classpath for Bumblebee, Chipmunk and Dolphin on Linux and Windows
  src/main/java/org/gradle/profiler/studio/launcher/StudioConfigurationProvider.java
  src/test/groovy/org/gradle/profiler/studio/launcher/StudioConfigurationProviderTest.groovy
Labels: bug, @execution

#445 Disable downloading of external annotations for Android Studio and IntelliJ
  src/test/groovy/org/gradle/profiler/AndroidStudioIntegrationTest.groovy
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/GradleProfilerProjectManagerListener.java
Labels: bug, @execution
