Repository gradle/gradle-profiler, pull requests merged in 2022-03, with the labels that each got.

#406 Add support to run profiler with IntelliJ
  src/main/java/org/gradle/profiler/studio/launcher/LauncherConfigurationParser.java
  src/main/java/org/gradle/profiler/studio/launcher/StudioConfigurationProvider.java
Labels: @execution, internal

#407 Upgrade versions to support building and running on M1 macs
  build.gradle.kts
  package-lock.json
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfilerDownload.java
  src/main/java/org/gradle/profiler/yourkit/YourKitProfilerController.java
Labels: enhancement

#409 Add support for running YourKit on Windows
  src/main/java/org/gradle/profiler/yourkit/YourKit.java
  src/main/java/org/gradle/profiler/yourkit/YourKitJvmArgsCalculator.java
  src/test/groovy/org/gradle/profiler/YourKitProfilerIntegrationTest.groovy
Labels: enhancement, @execution

#410 Simplify Android Studio download
  buildSrc/src/main/kotlin/profiler.android-studio-setup.gradle.kts
Labels: internal
