Repository gradle/gradle-profiler, pull requests merged in 2023-01, with the labels that each got.

#463 Chrome traces: normalize file paths in build operation display names
  buildSrc/src/main/kotlin/profiler.embedded-library.gradle.kts
  subprojects/chrome-trace/build.gradle
  subprojects/chrome-trace/src/main/java/org/gradle/trace/listener/Gradle35BuildOperationListenerInvocationHandler.java
  subprojects/chrome-trace/src/main/java/org/gradle/trace/listener/Gradle40BuildOperationListenerInvocationHandler.java
  subprojects/chrome-trace/src/main/java/org/gradle/trace/listener/Gradle47BuildOperationListenerInvocationHandler.java
  subprojects/chrome-trace/src/main/java/org/gradle/trace/listener/Gradle50BuildOperationListenerInvocationHandler.java
  subprojects/chrome-trace/src/main/java/org/gradle/trace/util/FilePathUtil.java
  subprojects/chrome-trace/src/test/groovy/org/gradle/trace/listener/GradleBuildOperationListenerTest.groovy
Labels: bug

#466 Teamcity config changes
  .teamcity/patches/buildTypes/LinuxJava11.kts
  .teamcity/patches/buildTypes/LinuxJava8.kts
  .teamcity/patches/buildTypes/MacOSJava8.kts
  .teamcity/patches/buildTypes/WindowsJava11.kts
  .teamcity/patches/projects/_Self.kts
  .teamcity/settings/root-project.kt
Labels: internal

#468 Add arch into agent requirements
  .teamcity/settings/GradleProfilerTest.kt
  .teamcity/settings/Os.kt
  .teamcity/settings/extensions.kt
Labels: enhancement
