Repository gradle/gradle-profiler, pull requests merged in 2023-06, with the labels that each got.

#498 Fix deadlock for Android Studio sync
  README.md
  build.gradle.kts
  subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/system/AndroidStudioSystemHelper.java
Labels: bug

#501 Fix :javadoc task
  src/main/java/org/gradle/profiler/GradleBuildConfiguration.java
Labels: internal

#488 Add jmap output when creating a heap dump
  src/main/java/org/gradle/profiler/Main.java
  src/main/java/org/gradle/profiler/heapdump/HeapDumpProfiler.java
  src/test/groovy/org/gradle/profiler/HeapDumpIntegrationTest.groovy
  subprojects/heap-dump/src/main/java/org/gradle/trace/heapdump/HeapDump.java
Labels: enhancement
