Repository gradle/gradle-profiler, pull requests merged in 2023-05, with the labels that each got.

#486 Update to Gradle 8.1.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  subprojects/studio-plugin/build.gradle.kts
Labels: internal, dependencies

#489 Update CodeQL GitHub actions
  .github/workflows/codeql-analysis.yml
Labels: internal, dependencies

#491 Update profiler.android-studio-setup.gradle.kts
  buildSrc/src/main/kotlin/profiler.android-studio-setup.gradle.kts
Labels: internal

#494 Update RELEASING.md with the information about snapshot versions
  RELEASING.md
Labels: internal

#497 Remove the add to gh project action
  .github/workflows/add-to-gh-projects.yml
Labels: no-changelog
