Repository gradle/gradle-profiler, pull requests merged in 2024-10, with the labels that each got.

#576 Improve Maven benchmarking and add profiling support, take 2
  README.md
  src/main/java/org/gradle/profiler/BuildToolCommandLineInvoker.java
  src/main/java/org/gradle/profiler/BuildToolCommandLineScenarioDefinition.java
  src/main/java/org/gradle/profiler/CompositeProfiler.java
  src/main/java/org/gradle/profiler/InstrumentingProfiler.java
  src/main/java/org/gradle/profiler/Main.java
  src/main/java/org/gradle/profiler/Profiler.java
  src/main/java/org/gradle/profiler/ScenarioDefinition.java
  src/main/java/org/gradle/profiler/ScenarioLoader.java
  src/main/java/org/gradle/profiler/asyncprofiler/AsyncProfiler.java
  src/main/java/org/gradle/profiler/bazel/BazelScenarioInvoker.java
  src/main/java/org/gradle/profiler/buck/BuckScenarioInvoker.java
  src/main/java/org/gradle/profiler/buildscan/BuildScanProfiler.java
  src/main/java/org/gradle/profiler/chrometrace/ChromeTraceProfiler.java
  src/main/java/org/gradle/profiler/gradle/GradleScenarioDefinition.java
  src/main/java/org/gradle/profiler/gradle/GradleScenarioInvoker.java
  src/main/java/org/gradle/profiler/heapdump/HeapDumpProfiler.java
  src/main/java/org/gradle/profiler/jfr/JfrProfiler.java
  src/main/java/org/gradle/profiler/jprofiler/JProfilerProfiler.java
  src/main/java/org/gradle/profiler/maven/MavenScenarioDefinition.java
  src/main/java/org/gradle/profiler/maven/MavenScenarioInvoker.java
  src/main/java/org/gradle/profiler/yourkit/YourKitProfiler.java
  src/test/groovy/org/gradle/profiler/ProfilerIntegrationTest.groovy
Labels: enhancement

#569 Query phase system property in background to avoid CC miss
  src/main/java/org/gradle/profiler/buildscan/GradleEnterpriseAlreadyAppliedInitScript.java
  src/main/java/org/gradle/profiler/buildscan/GradleEnterpriseInitScript.java
Labels: bug

#581 GitHub: set up dependency actions
  .github/dependabot.yml
  .github/workflows/dependency-review-action.yml
  .github/workflows/dependency-submission.yml
Labels: no-changelog
